version: "3.8"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    restart: unless-stopped

    # Нужны для поднятия интерфейса wg0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    # Проброс портов: 51821 — веб-UI (TCP), 51820 — VPN (UDP)
    ports:
      - "51821:51821/tcp"
      - "51820:51820/udp"

    # Храним конфиги на хосте
    volumes:
      - ./data:/etc/wireguard

    # Важные sysctl для форвардинга
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv6.conf.all.disable_ipv6: "0"
      net.ipv6.conf.all.forwarding: "1"

    environment:
      # читаются из .env
      - TZ=${TZ}
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_MTU=${WG_MTU}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - WG_PERSISTENT_KEEPALIVE=${WG_PERSISTENT_KEEPALIVE}
